version: '3'

services:
  ib-gateway:
    build:
      context: ./docker/ib_gateway
    restart: always
    environment:
      TWS_USERID: ${TWS_USERID}
      TWS_PASSWORD: ${TWS_PASSWORD}
      TRADING_MODE: ${TRADING_MODE}
      VNC_SERVER_PASSWORD: ${VNC_SERVER_PASSWORD}
    ports:
      - "127.0.0.1:4001:4001"
      - "127.0.0.1:4002:4002"
      - "127.0.0.1:5900:5900"

  php:
    container_name: php
    build:
      context: ./docker/php
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - SIGNAL_RECEIVER_URL=${SIGNAL_RECEIVER_URL}
    volumes:
      - ./php:/var/www

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./php:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log/nginx
    depends_on:
      - php
    ports:
      - "81:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
 
