version: '3'

services:
  php:
    container_name: php
    build:
      context: ./docker/php
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    user: "1000:1000"
    volumes:
      - ./:/var/www

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log/nginx
    depends_on:
      - php
    ports:
      - "81:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"