parameters:
    signal_receiver_url: '%env(resolve:SIGNAL_RECEIVER_URL)%'
    signal_receiver_url_second: '%env(resolve:SIGNAL_RECEIVER_URL_SECOND)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
