parameters:
    signal_receiver_url: '%env(resolve:SIGNAL_RECEIVER_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    guzzle:
        class: \GuzzleHttp\Client

    App\Service\R2BC\R2BCSignalHandler:
        arguments:
            $client: '@guzzle'
